### ISSUE TITLE
JPEG

### ISSUE THREAD

**Issue by sboukortt** [fabiorug/JXL-IMG-quality-calculator#1]
Hi Fabiorug, thank you for your feedback.

I couldn’t find how to get the original JPEG. Could you please share it?

Thanks.

**Comment by fabiorug** [comment]
Hi! I edited the comment deleting the link (because I found is the official JPEG XL thread and not random compressor thread, so I got the rules wrong). Also it don't work for all images. I'm not a image compression engineer so I don't know what measurements mean, but there are certain category managers like imageranger; who also has the options to delete low quality image. But anyway if you're an engineer, I recommend you to study and not use these metods, these could be useful only for over-compression.

Files size of your whatever jpeg image in bytes (I don't know if you should use a recompressor like fpsk29 on Encode.su to get an appropriate file size or the vardct recompression (Brunsli was deleted because they want to simplify specification and maybe have fast decoding speed in lossless recompressed images in Jpeg XL codec, now if you don't write -j (lossy jpg command) it will be compressed with a method based on VarDCT). But could improve if you use a recompressor or paq, but I didn't use it in my 2° example so I don't recommend it.


/1877/55345/7
4 digit for distance butteraugli
digit at right used for speed if the speed is available


(don't change 7 with an other number)
Then you can digit in cmd the -d (for Jpeg XL).

**Comment by fabiorug** [comment]
Also some images needs editing in features (JPEG Xl is more strong in that), that's why I commented with -s 9 you can have women looking like basketball player even at -d 1.
On ENCODE.SU developers (Jyrki Alakuijala and Jon Sneyers) usually post in two threads what it will be in the next update.

**Comment by fabiorug** [comment]
Jpeg XL average saving is 38.9% so likely if you get more compression, original image is a bit overcompressed.

**Comment by fabiorug** [comment]
Also, this method could be good if you want a more lucid image than original, if the original is compressed not good. I don't recommend using my draft for original compressed file.

**Comment by sboukortt** [comment]
Thank you for that info! To be clear, I am part of the development team, and we are always eager for issues to reproduce, so if you notice any more problems, don’t hesitate to send us the images and commands to replicate your findings. We would be more than happy to take a look.

Thanks. :)
